trigger: none

pool: 'DevOps Deployment'

variables:
- template: variables.yml 

steps:
- template: template.yml
  parameters:
    environment: 'prod'
    user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_PROD)